// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AriaCheckedController from "./aria_checked_controller"
application.register("aria-checked", AriaCheckedController)

import AriaExpandedController from "./aria_expanded_controller"
application.register("aria-expanded", AriaExpandedController)

import HamburgerController from "./hamburger_controller"
application.register("hamburger", HamburgerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SelectMenuController from "./select_menu_controller"
application.register("select-menu", SelectMenuController)

import TablistController from "./tablist_controller"
application.register("tablist", TablistController)
